development:
  adapter: postgresql
  encoding: unicode
  database: countrypedia_development
  pool: 5
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: countrypedia_test
  pool: 5
  password:
