Country.create(region_code: "150", woeid: "", code2: "", code3: "", name: "netherlands")
Country.create(region_code: "150", woeid: "", code2: "", code3: "", name: "andorra")
Country.create(region_code: "150", hens", woeid: "", code2: "", code3: "", name: "greece")
Country.create(region_code: "150", capital: "belgrad", woeid: "23424829", code2: "de", code3: "deu", name: "serbia")
Country.create(region_code: "150", capital: "berlin", woeid: "23424829", code2: "de", code3: "deu", name: "germany")
Country.create(region_code: "150", capital: "bern", woeid: "", code2: "", code3: "", name: "switzerland")
Country.create(region_code: "150", capital: "bratislava", woeid: "", code2: "", code3: "", name: "sloviakia")
Country.create(region_code: "150", capital: "brussels", woeid: "", code2: "", code3: "", name: "belgium")
Country.create(region_code: "150", capital: "bucharest", woeid: "", code2: "", code3: "", name: "romania")
Country.create(region_code: "150", capital: "budapest", woeid: "", code2: "", code3: "", name: "hungary")
Country.create(region_code: "150", capital: "chisinau", woeid: "", code2: "", code3: "", name: "moldavie")
Country.create(region_code: "150", capital: "copenhagen", woeid: "", code2: "", code3: "", name: "denmark")
Country.create(region_code: "150", capital: "dublin", woeid: "", code2: "", code3: "", name: "ireland")
Country.create(region_code: "150", capital: "helsinki", woeid: "", code2: "", code3: "", name: "finland")
Country.create(region_code: "150", capital: "kiev", woeid: "", code2: "", code3: "", name: "ukraine")
Country.create(region_code: "150", capital: "lisbon", woeid: "", code2: "", code3: "", name: "portugal")
Country.create(region_code: "150", capital: "london", woeid: "23424975", code2: "gb", code3: "gbr", name: "unitedkingdom")
Country.create(region_code: "150", capital: "madrid", woeid: "", code2: "", code3: "", name: "spain")
Country.create(region_code: "150", capital: "paris", woeid: "23424819", code2: "fr", code3: "fra", name: "france")
Country.create(region_code: "150", capital: "wien", woeid: "", code2: "", code3: "", name: "austria")
